---
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
role_name_check: 1
provisioner:
  name: ansible
verifier:
  name: ansible
