---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      become: true
      package:
        name:
          - unzip
          - python3-setuptools
          - python3-requests

    - name: Install OS packages (Debian-based)
      become: true
      when: ansible_os_family == 'Debian'
      package:
        name:
          - python3-pkg-resources

    - name: Install pip dependencies on controlling host
      pip:
        name: 
          - netaddr
          - jmespath
          - virtualenv
          - requests
