---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      become: true
      package:
        name: 
          - unzip
          - python3-setuptools

    - name: Install pip dependencies on controlling host
      pip:
        name: 
          - netaddr
          - jmespath
          - virtualenv
          - requests
