---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      package:
        name: unzip
      become: true

    - name: Install pip setuptools on controlling host
      pip:
        name:
          - setuptools

    - name: Install pip dependencies on controlling host
      pip:
        name: 
          - netaddr
          - jmespath
          - virtualenv
          - requests
